name: Mirror to GitLab test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://asmae.bouazzati1234:${{ secrets.token }}@gitlab.com/ass9682519/selinum-demo.git"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "asmae.bouazzati1234"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "57770625"
        GITHUB_TOKEN: ${{ secrets.token }}